[package]
name = "octopus-engine"
version = "0.2.0"
edition = "2021"
authors = ["Richard Bates <rich.bates@protonmail.com>"]
description = "Trading engine algorithm library ğŸ™"
repository = "https://github.com/richo225/octopus"
license-file = "../LICENSE.txt"
readme = "../README.md"
keywords = ["trading", "engine", "octopus", "platform"]
categories = ["algorithms", "finance"]

[dependencies]
serde = { version = "1.0.163", features = ["derive"] }
